### ISSUE TITLE
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by KScript92** [tomguluson92/PRNet_PyTorch#11]
The following error is output in train.py.
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
origin, gt_uv_map = transform_img(origin), transform_img(gt_uv_map)
I keep getting errors in this section, how do I fix it?

**Comment by eshuka** [comment]
I change transform_img

    transform_img = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(FLAGS["normalize_mean"], FLAGS["normalize_std"])
    ])

to

    transform_img = transforms.Compose([
        # transforms.ToTensor(),
        transforms.Normalize(FLAGS["normalize_mean"], FLAGS["normalize_std"])
    ])

and it worked.

**Comment by tomguluson92** [comment]
> I change transform_img
> 
> ```
> transform_img = transforms.Compose([
>     transforms.ToTensor(),
>     transforms.Normalize(FLAGS["normalize_mean"], FLAGS["normalize_std"])
> ])
> ```
> 
> to
> 
> ```
> transform_img = transforms.Compose([
>     # transforms.ToTensor(),
>     transforms.Normalize(FLAGS["normalize_mean"], FLAGS["normalize_std"])
> ])
> ```
> 
> and it worked.

Thanks
