### ISSUE TITLE
按照你的方法生成的UV pos map中的jpg图片好像有错

### ISSUE THREAD

**Issue by ReverseSystem001** [tomguluson92/PRNet_PyTorch#4]
![original](https://user-images.githubusercontent.com/23073337/69425802-98d2d280-0d66-11ea-828d-d7e8943d27ad.jpg)

生成uv_pos_map时相应的jpg original图像文件是这样的,是不是错了??

**Comment by ReverseSystem001** [comment]
![original2](https://user-images.githubusercontent.com/23073337/69425920-d20b4280-0d66-11ea-930b-fcdf343735fa.jpg)

**Comment by tomguluson92** [comment]
您可以看看原作者的实现效果, 进行比较. 谢谢^.^

**Comment by ReverseSystem001** [comment]
> 您可以看看原作者的实现效果, 进行比较. 谢谢^.^

恩恩,谢谢回复
