### ISSUE TITLE
poor inference.

### ISSUE THREAD

**Issue by alchemi5t** [tomguluson92/PRNet_PyTorch#5]
Hello,

I am trying to run the landmark detector on a webcam video stream and plot the landmarks but the landmarks are very unstable and almost always far off from what is correct. This is the piece of code that i am running for plotting the landmarks. How can i fix this?

```
transform_img = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
prn = PRN("results/latest.pth")
for frame from cam:  #psuedo code
    frame_temp = cv2.resize(frame[int(bbox[1]*0.7):int(bbox[3]*1.3),int(bbox[0]*0.7):int(bbox[2]*1.3)],     (256, 256)) #sending only the face portion of the video stream
    image_t = transform_img(frame_temp)
    image_t = image_t.unsqueeze(0)
    pos = prn.net_forward(image_t.cuda())


    out = pos.cpu().detach().numpy()
    pos = np.squeeze(out)
    cropped_pos = pos * 255
    pos = cropped_pos.transpose(1, 2, 0)
    kpt = prn.get_landmarks(pos)
    cv2.imshow('sparse alignment', plot_kpt(frame_temp, kpt))

cv2.waitKey(10)




```

I am running this repeatedly over each frame from the web cam.

**Comment by alchemi5t** [comment]
what exactly is this variable 'self.uv_kpt_ind'?

**Comment by tomguluson92** [comment]
The point is somewhat related to the model itself. I think you can train prnet with more data.

**Comment by tomguluson92** [comment]
> uv_kpt_ind

official landmark position of shape `2 x 68`

**Comment by alchemi5t** [comment]
did you try to reproduce the gifs in the readme? they seem to be spot on while my output seems to be total garbage.

Also, so you're telling me my code snippet is not logically erroneous, right?

> official landmark position of shape 2 x 68

so the net is using this to infer on all test data? I'll read up on this, don't exactly understand how this is working.

**Comment by tomguluson92** [comment]
> did you try to reproduce the gifs in the readme? they seem to be spot on while my output seems to be total garbage.
> 
> Also, so you're telling me my code snippet is not logically erroneous, right?
> 
> > official landmark position of shape 2 x 68
> 
> so the net is using this to infer on all test data? I'll read up on this, don't exactly understand how this is working.

Yep, the inference code you posted is the same as me. I recommend you transform all the data psoted as in the original PRNet repo (not only `300WLP`) and train with it.
